version: "3.4"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"